### ISSUE TITLE
Decode event data with structs

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#108]
## 📚 Context

When testing event emission with forge, we need to decode event data using `abi.decode`. Currently, we are decoding it field-by-field, which is quite cumbersome. The test code it not very readable and prone to errors.

```solidity
(a, b, c) = abi.decode(entry.data, (address, bytes32, address));
```

## ✔️ Solution

In #106, @xdaniortega defined event data as a struct and decoded it field-by-field. This method lets use check each field by their field name.

```solidity
(event.validators, event.quorum) = abi.decode(entry.data, (address[], Quorum));
```

An improvement is to let Solidity do this field-by-field decoding behind the scenes.

```solidity
event = abi.decode(entry.data, (EventData));
```

This pattern can be applied whenever we have a call to `vm.getRecordedLogs()` followed by a loop that check each event.

**Comment by xdaniortega** [comment]
Thanks for the shoutout :) It's definitely very helpful for more complex objects, by doing this you can handle arrays and different variables inside objects as Quorum.

**Comment by guidanoli** [comment]
I've just found out that event parameters are encoded using [packed encoding](https://docs.soliditylang.org/en/latest/abi-spec.html#encoding-of-indexed-event-parameters).
This means that this method will (sadly) not work for events with dynamically-sized types.

**Comment by guidanoli** [comment]
In actuality, event data IS encoded in strict mode, but when decoding structs that contain variable length fields, the ABI adds an extra offset, which is not contained in the encoded event data.

So, if the event data has no variable-length fields, you can use `abi.decode` with the struct.
Otherwise, decode the fields individually.
