### ISSUE TITLE
Test array elements and length

### ISSUE THREAD

**Issue by xdaniortega** [cartesi/rollups-contracts#111]
## 📚 Context

The problem we are addressing involves the need for a utility function within the `TestBase.sol` Solidity contract. This utility function, named `assertEq(array, array)`, is required to compare two address arrays and ensure that they have the same length and contain identical elements.

Thanks to @guidanoli for suggesting this issue.

**Comment by xdaniortega** [comment]
I just found a way to compare two different arrays, independently of the type (uint256, bytes32 ....).

We'll take advantage of internal functions in foundry `checkEq0`:
```
    function checkEq0(bytes memory a, bytes memory b) internal pure returns (bool ok) {
        ok = true;
        if (a.length == b.length) {
            for (uint i = 0; i < a.length; i++) {
                if (a[i] != b[i]) {
                    ok = false;
                }
            }
        } else {
            ok = false;
        }
    }
```
And to convert from array to bytes we're going to use `abi.encodePacked`.

By doing this we will improve test readability from changing from:
```
//Check Validators length in decoded data should match the data passed to the event
assertEq(
    _quorumValidators.length,
    quorumEvent.quorumValidators.length
);

//Compare each validator
for (uint j = 0; j < quorumEvent.quorumValidators.length; j++) {
    assertEq(
        _quorumValidators[j],
        quorumEvent.quorumValidators[j]
    );
}
```
to:
```
 checkEq0(abi.encodePacked(quorumEvent.quorumValidators), abi.encodePacked(_quorumValidators));
``

**Comment by guidanoli** [comment]
Hey Daniel, my suggestion was for you to add this function directly in your PR...
I've left a [code snippet](https://github.com/cartesi/rollups-contracts/pull/106#discussion_r1352922995) there.

**Comment by xdaniortega** [comment]
Hey @guidanoli completely! The possible scenario came up with developing a new function for all the tests made me create this issue as is something general. Now we can see that the scope of the improvement is very reduced as the new solution is simpler than expected.
