### ISSUE TITLE
Make portals own assets again

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#112]
## 📚 Context

Digital assets come in many flavors: Ether, ERC-20 tokens, NFTs, Multi-tokens... To support the great variety of digital assets, we created smart contracts called **portals**. The portal analogy is used to communicate the idea of "teleporting" assets from the base layer (where smart contracts run) to the execution layer (where the DApp back-end runs). In reality, assets are locked in a special smart contract, where they are only released through vouchers emitted by the application.

The idea of portals has been around since the very first release of Cartesi Rollups, due to the early demand for native payment options. Their implementation, however, has changed considerably. Let's revisit those early versions for the sake of historical perspective.

- **0.1**: The Ether portal, ERC-20 Portal, and DApp contract were separate from each other. Each DApp had their own set of portals! There was also a separate contract just for dealing with outputs. **The portals owned the assets!** The portals communicated with the input contract to notify the DApp of new deposits, and had a permissioned entry point from the output contract to execute withdrawals.
- **0.2**: [EIP-2535](https://eips.ethereum.org/EIPS/eip-2535) was adopted. Most contracts were converted into facets, which shared the same storage context, and could communicate with each other through libraries. This means that **the diamond (which included portals and other facets) owned the assets!** Also, the ERC-721 Portal (in the form of a facet) was added!
- **0.9**: EIP-2535 was dropped, and the architecture was simplified! Now, the DApp no longer shares the same storage context as the portals. Portals are separate contracts again, but they are shared amongst all contracts. However, **it is now the DApp that owns the assets!** Also, the ERC-1155 Portal was added!

As you can see, the role of holding assets slowly transitioned from the portals to the DApp contract. The gray area in-between being version 0.2, where portals were facets of a diamond, which was the DApp contract itself.

Another big shift was making portals shared. This meant that the DApp back-end could know the address from which deposit inputs would come before even deploying the DApp contract. This also reduced deployment costs per DApp.

On October 21st, a discussion between @gligneul, @tuler, @edubart, @pedroargento and I took place in the `#sunodo` channel, on the Cartesi Discord Server. The conclusion was that if we made portals own the assets again, this would bring two major benefits:

- The total value locked (TVL) of all Cartesi DApps would be much easier to calculate
- The DApp back-end wouldn't need to know the DApp address in order to generate withdrawal vouchers

It is worth noting that this change would increase the gas cost of asset deposits and withdrawals. Still, we believe this increase will be negligible when compared to the current gas cost of executing any voucher.

## ✔️ Solution

- Add a transfer function to each portal, that:
  - transfers assets from `msg.sender` to some other address **internally**
  - adds a deposit input to the recipient's input box
  - makes no interaction with the token contract whatsoever!
- Add a withdrawal function to each portal, that:
  - deducts assets from `msg.sender` **internally**
  - does not add an input to the recipient's input box
  - interacts with the token contract to actually transfer the assets to the recipient
- Add a withdrawal function that assumes `recipient = msg.sender`
- Update the deposit function of each portal to:
  - transfer the assets to the portals themselves
  - do some internal accounting of which assets belong to which DApps **internally**

You may ask why do we need a transfer function and a withdrawal function? Well, if you want to transfer assets to another DApp, the `transfer` function is the way to go, since it also adds a deposit input. Previously, you might've had to call `approve` on the token contract and then call the `deposit*` on the portal contract, but this was error-prone and cumbersome. Now, you can just call `transfer` and the token transfer is done internally in the portal.

So... why do we need a withdrawal function? Well, if the recipient is not a DApp, but instead an EOA, then they might want to actually have hold of the asset, right? In this case, they would call the withdrawal function.

**Comment by pedroargento** [comment]
I like this idea, but as I understand it was discussed on the transition to 0.9 and it was decided to keep the funds in the DApp contract. So I think its important to revisit why this decision was made and what changed (or what we understand better about the issue) to make sure we are not introducing problems detected back then. @felipeargento can help with this discussion.

There other things we also need to discuss:
- Cost issues of the extra accounting to mange balances in the portal.
- DApp recovery and upgradability.
- Rollups upgradability, because it would remove the stateless propriety of the Portals.

**Comment by guidanoli** [comment]
> So I think its important to revisit why this decision was made and what changed.

From what I remember, we chose to keep the assets in the DApp contract simply because the portals would have to do a lot of extra accounting, which would, in turn, increase the gas cost of deposits and withdrawals. And... this is still true! But maybe what we didn't notice at the time was that this change would also bring some nice benefits, such as those mentioned above.

> Cost issues of the extra accounting to mange balances in the portal.

We can run some benchmarks, to assess the actual impact in terms of gas cost.

> DApp recovery and upgradability.

Portals would certainly help in this task! Suppose you own a DApp that just fell into an infinite loop. You then decide to change the consensus to another consensus that claims an epoch hash that contains vouchers that transfer all of your DApp's assets to the new version of your DApp, with a new template hash.

> Rollups upgradability, because it would remove the stateless propriety of the Portals.

Suppose we've just deployed the new portals that hold assets. Later, we modify something in the portals or in the input box that triggers a redeployment of those contracts. Now, to calculate the TVL, one would have to take into account versions 1 and 2 of each portal set. And this goes on forever. So the number of contracts you would have to listen to would grow linearly with the number of versions.

**Comment by ZzzzHui** [comment]
> Solution:
> ...
> - Add a withdrawal function that assumes recipient = msg.sender

msg.sender is the dapp itself, so this is transferring the asset from portal to the dapp itself? If this doesn't happen often, then we can simply use the more general withdraw function.

> > DApp recovery and upgradability.
>
> Portals would certainly help in this task! Suppose you own a DApp that just fell into an infinite loop. You then decide to change the consensus to another consensus that claims an epoch hash that contains vouchers that transfer all of your DApp's assets to the new version of your DApp, with a new template hash.

For the proposed portal to transfer all assets from old dapp to new dapp, the portal would need to also keep a record of what kind of tokens the dapp has. For example, the ERC20 portal keeps a record of what erc20 tokens the dapp has. This introduces additional gas as well. But if the portal doesn't keep this record, then the dapp upgradability is similar between the current infrastructure and the proposed one: need a voucher for every kind of asset, the current destination is token address while the proposed destination would be the portal. What do you think?

**Comment by pedroargento** [comment]
There is also a narrative angle we should think about and discuss with the community: Should the funds of be mixed since we are working with Dapp-chains? Should we focus on making TVL a relevant metric?

**Comment by ZzzzHui** [comment]
The current issue was raised initially because the offchain machine needs to know dapp's onchain address, in order to generate vouchers to withdraw ethers or erc721. 
- For ether withdraw, payable voucher addresses it;
- For ERC721, not sure if generating voucher targeting `ERC721_token.approve(address to, uint256 tokenId)` can be a work-around. After voucher execution, address `to` would have to then call `ERC721_token.safeTransferFrom(address from, address to, uint256 tokenId)`. This last step is what I'm not sure whether the address `from` is obtainable or not.
- For ERC1155, this is tricky. Approval can only be set for owner's all ERC1155 tokens.

**Comment by guidanoli** [comment]
> msg.sender is the dapp itself, so this is transferring the asset from portal to the dapp itself? If this doesn't happen often, then we can simply use the more general withdraw function.

Not always. If the DApp called `transfer` to an EOA, then the EOA will have to call `withdraw` to actually have hold of the tokens. I am thinking that `transfer` is a safe call to make, not assuming whether the recipient is a DApp or an EOA. If the recipient is a DApp, it will receive an input. Otherwise, it will need to call `withdraw`.

**Comment by ZzzzHui** [comment]
> > msg.sender is the dapp itself, so this is transferring the asset from portal to the dapp itself? If this doesn't happen often, then we can simply use the more general withdraw function.
> 
> Not always. If the DApp called `transfer` to an EOA, then the EOA will have to call `withdraw` to actually have hold of the tokens. I am thinking that `transfer` is a safe call to make, not assuming whether the recipient is a DApp or an EOA. If the recipient is a DApp, it will receive an input. Otherwise, it will need to call `withdraw`.

Oh the portal holds assets for EOA too. Ok I see

**Comment by guidanoli** [comment]
> Should the funds of be mixed since we are working with Dapp-chains? Should we focus on making TVL a relevant metric?

Now that I think of it, I think not. What do you think, @tuler?

**Comment by tuler** [comment]
The smart contract that powers one DApp is the same (code) that powers every DApp. A vulnerability on the code affects all DApps. I believe the global TVL is a relevant metric, as well as individual VLs.

Calculating the global TVL is still possible, through watching the factory. Actually the hardest part is perhaps calculating the subtraction of value, which requires voucher execution monitoring, and not even directly related to the portal.

So this may be one of the decision factors, but the problem is more complex.

**Comment by guidanoli** [comment]
> The smart contract that powers one DApp is the same (code) that powers every DApp. A vulnerability on the code affects all DApps.

Thanks for touching on the security side of the issue! Well, I could argue that a single contract that holds all the TVL is less safe than multiple contracts with each a fraction of the TVL, no?

> Calculating the global TVL is still possible, through watching the factory. Actually the hardest part is perhaps calculating the subtraction of value, which requires voucher execution monitoring, and not even directly related to the portal.

I wouldn't even consider the voucher that withdraw assets in the calculation of the TVL. Maybe an application has 10 ETH, and emitted a voucher that withdraws 1 ETH, but 10 ETH are still technically locked in the application, even though it is possible to withdraw 1 ETH. When this voucher executed, then the TVL (for that application) is 9 ETH.

**Comment by pedroargento** [comment]
You have to consider vouchers execution if you are calculating the TVL by listening to deposit events and not querying blockchain directly, which I think it was what he meant by monitoring vouchers execution. But my point was not about the calculation, it was more philosophical if we should care about TVL.

Its the same DApp code and same vulnerabilities, but we would be adding a new surface of attack by implementing ourselves the accounting mechanisms in the portal that make sure each DApp can only touch its own funds. Right now, there is one more level of compartmentalization guaranteed by the protocol.

**Comment by miltonjonat** [comment]
> I wouldn't even consider the voucher that withdraw assets in the calculation of the TVL. Maybe an application has 10 ETH, and emitted a voucher that withdraws 1 ETH, but 10 ETH are still technically locked in the application, even though it is possible to withdraw 1 ETH. When this voucher gets eventually executed, then the TVL (for that application) would be 9 ETH.

This is the idea for the Honeypot: it is only considered cracked if the money is withdrawn.
Other than that, calculating VL by checking the on-chain contracts much more straightforward IMHO. You **could** still monitor deposits and withdrawal voucher executions of course, but I'm not sure in which scenarios one would prefer that.

**Comment by guidanoli** [comment]
> In general, calculating VL by checking the on-chain contracts is a much more straightforward approach IMHO.

Not only is it the straightforward way, but the de facto way of calculating VL.

**Comment by guidanoli** [comment]
As noted by @pedroargento, this feature might be superseded by base layer access, through which deposits would be detected by listening to events emitted by contracts.
