### ISSUE TITLE
Improve `History`

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#115]
## 📚 Context

There are some usability issues in `History` that can be improved.
For example, there is no entry point for querying the number of claims submitted to a given DApp.

## ✔️ Solution

- Add `getNumberOfClaims` function
- Add `getClaim` function that takes a `uint256` instead of `bytes`

**Comment by pedroargento** [comment]
Please apply the naming change discussed here: https://github.com/cartesi/rollups-contracts/issues/142

**Comment by guidanoli** [comment]
Superseded by #152.
