### ISSUE TITLE
Investigate the gas cost for deploying `QuorumHistoryPairFactory` deterministically

### ISSUE THREAD

**Issue by ZzzzHui** [cartesi/rollups-contracts#127]
## 📚 Context

When deploying the `QuorumHistoryPairFactory` deterministically, specifically we are talking about the deployment of the history [here](https://github.com/cartesi/rollups-contracts/blob/0f89f517b29ea0d94145b06071fd10e5af579d8c/onchain/rollups/contracts/consensus/quorum/QuorumHistoryPairFactory.sol#L67), we use an auxiliary function `calculateCompoundSalt` (originally proposed by Gui) to compute the compound salt of all parameters instead of directly using `_salt`. 
By doing this, attackers will not be able to front run the deployment of history by using the same `_salt` but different `_validators` and `_shares`, thus occupying the deterministic deployment address of history.
However, this attack is expensive for attackers because there are 2 contract deployments. And the attack consequence is likely not severe, because if being front-run, the user can simply choose another salt. 

The users' cost to prevent this attack, via calling `calculateCompoundSalt`, is what to be investigated under this issue. 
This issue is specifically for `QuorumHistoryPairFactory` because its calculation of compound salt involves 2 arrays whose size can be large if the quorum is large.

**Comment by guidanoli** [comment]
Superseded by #130 (see solution in comments).
