### ISSUE TITLE
Remove `success` from ERC-20 deposit input

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#132]
## 📚 Context

Issue #113 suggests making the ERC-20 portal check if `success` is `true`, keeping the input ABI intact. However, the DApp still receives this field and has to check it, even though it is guaranteed to be `true` at the smart contract level.

## ✔️ Solution

Remove this value from the ERC-20 deposit input, since it is guaranteed to be `true`.

## 📈 Subtasks

- [ ] Change the ERC-20 Portal
- [ ] Update the tests

**Comment by ZzzzHui** [comment]
This will wait until PR #136 is merged and branch `next` is rebased
