### ISSUE TITLE
Permissionless History

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#133]
## 📚 Context

In our current architecture, we have the following cyclical dependency: a consensus contract delegates claim storage and retrieval to a `History` contract, which is owned by the consensus contract itself. This creates some problems when deploying these contracts deterministically. You can read more about these problems in issue #130.

This problem is relevant because it enables an attack on the factories where anyone that knows the set of parameters for deploying the consensus-History pair can effectively prevent the successful deployment of the pair, by communicating with the consensus factory directly. This problem is a blocker for the creation of the `QuorumHistoryPairFactory` and `QuorumFactory`, since they would also suffer from this attack. It affects the users of `AuthorityHistoryFactory`, who might have agreed upon a set of parameters, but are not guaranteed of having their contracts deployed successfully.

## ✔️ Solution

One of the proposed solutions was to add another deterministic deployment entry point to the factories that takes the `msg.sender` into consideration when calculating the to-be-deployed contract. This entry point would be used by pair factories to avoid malicious actors from calling the underlying factories on their behalf (assuming it is not possible to fabricate hash collisions).

There is another solution which removes the need for these pair factories altogether, which is to make the `History` contract permissionless, meaning that anyone can submit claims to it. This creates several breaking changes that cascade to several contracts that directly or indirectly depend on the `History` contract. We believe, however, that this would bring major simplification to our architecture. For example, this would remove the need for a `HistoryFactory`, since it would be completely permissionless. We can deploy it just like we already do with the `InputBox` contract.

## 📈 Subtasks

Here is the dependency graph of contracts affected by this change. Contracts in red will be removed, those in yellow will have API-breaking changes.

```mermaid
flowchart BT
    classDef removed stroke:#f00
    classDef changed stroke:#ff0

    Authority:::changed --> IHistory:::changed
    History:::changed --> IHistory
    AuthorityFactory:::changed --> IAuthorityFactory:::changed --> Authority
    HistoryFactory:::removed --> IHistoryFactory:::removed --> History
    AuthorityHistoryPairFactory:::removed --> IAuthorityHistoryPairFactory:::removed --> AuthorityFactory
    IAuthorityHistoryPairFactory --> HistoryFactory
```

Let's list the changes by contract.

### `IHistory`
- Add `_submitter` parameter to `getClaim` function
- Remove `migrateToConsensus` function

## `History`
- Remove inheritance from `Ownable` contract
- Add `submitter` parameter to `NewClaimToHistory` event
- Rename `NewClaimToHistory` event as `ClaimSubmission`
- Remove `_owner` parameter from constructor

## `IHistoryFactory`
- Remove interface

## `HistoryFactory`
- Remove contract

## `Authority`
- Add `_history` parameter to constructor
- Remove `migrateHistoryToConsensus` function

## `AuthorityFactory`
- Add `_history` parameter to all functions

## `IAuthorityHistoryPairFactory`
- Remove interface

## `AuthorityHistoryPairFactory`
- Remove contract

**Comment by pedroargento** [comment]
What happens when the DApp migrates consensus with a permissionless history? Its going to be harder to access the list of claims made by the correct authority, right? We should think about what it affects.

**Comment by guidanoli** [comment]
> What happens when the DApp migrates consensus with a permissionless history? Its going to be harder to access the list of claims made by the correct authority, right? We should think about what it affects.

Why would it be harder to access the list of claims made by the correct authority?

**Comment by pedroargento** [comment]
Because we will be indexing by (submitter, DApp). To get a past claim, I will need to know who was the correct authority at the time the claim was posted. If I want to get the history of a DApp that changed authority, I would need to know when the change happened to get the list: `[(consensus1, DApp), (consensus1, DApp), (consensus1, DApp), (consensus2, DApp), ...]`

Since its permissionless, we cant guarantee what will be in the history `(consensus2, DApp)` before the change.

**Comment by guidanoli** [comment]
There is no mix-and-match of claims from different submitters. The DApp asks its consensus for the claim. If the consensus uses the permissionless history, it will ask for the claim submitted by the consensus itself.

**Comment by guidanoli** [comment]
If a DApp changes its consensus, the new consensus will have to provide claims for all inputs from the start. It may do some weird engineering under-the-hood to retrieve claims from old consensus, but that's totally up to the consensus.

**Comment by ZzzzHui** [comment]
I see 2 ways:
1. new consensus needs to copy all old claims. So it's like all claims were submitted from the new consensus
2. each consensus keeps track of the claim index from which they started functioning and also the previous consensus. If the claim index is prior than that, ask the previous consensus. This keeps backtracking, until it reaches the correct consensus. Overall, it's like a linked list. Although it would get even more complicated if a consensus was chosen more than once, then there would be multiple claim indexes from which they started working.

**Comment by guidanoli** [comment]
I think the first way is simpler.

**Comment by guidanoli** [comment]
Superseded by #152.
