### ISSUE TITLE
Upgrade solidity pragma to ^0.8.13

### ISSUE THREAD

**Issue by ZzzzHui** [cartesi/rollups-contracts#138]
@guidanoli proposed to use a type-safe way to encode function calls (see [here](https://github.com/cartesi/rollups-contracts/issues/42#issuecomment-1791371612)), which is already adopted in branch `feature/blockchain-agnostic-inputs`.
Since this new feature `abi.encodeCall` was introduced in 0.8.11 and bug fixed in 0.8.13 ([ref](https://soliditylang.org/blog/2022/03/16/encodecall-bug/)), we'll upgrade solidity to `pragma solidity ^0.8.13;`

**Comment by guidanoli** [comment]
Actually, now v2 will not trigger a redeployment of all contracts.
Therefore, let's only fix this by the end of v2, only for the contracts that were changed.
