### ISSUE TITLE
Apply new input/payload nomenclature to portals

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#140]
## 📚 Context

With #84, we'll rename `input` in the `addInput` function as `payload`, since we are now calling "input" the blob that is forwarded to the machine. This will trigger the deployment of a new `InputBox` contract, and, consequently, the deployment of new portals and relays. We should, therefore, take the opportunity to propagate this renaming to the portals and relays.

## ✔️ Solution

Rename `input` as `payload` in portals and relays.

## 📈 Subtasks

- [ ] Ether portal
- [ ] ERC-20 portal
- [ ] ERC-721 portal
- [ ] ERC-1155 portal
- [ ] DApp address relay

**Comment by ZzzzHui** [comment]
Hey @guidanoli , these were already addressed in PR #89, as they are all part of the "renaming input related terms"

**Comment by guidanoli** [comment]
@ZzzzHui I'll link #89 to this issue then.
