### ISSUE TITLE
Comply with Solidity style guide

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#164]
## 📚 Context

Solidity specifies the following [style guide](https://docs.soliditylang.org/en/v0.8.23/style-guide.html). There are some guidelines we don't follow.
The most relevant is the naming convention of function parameters, and internal/private functions and state variables.

## ✔️ Solution

Update contracts to comply with the style guide.
We should take the opportunity of v2 to do this refactoring, since all contracts will be redeployed anyway.
Also, check if the guidelines can be checked and enforced by `prettier`.

**Comment by guidanoli** [comment]
## General pipeline

- Add `_` prefix to internal/private state variable names (if they don't have it already)
- Add `_` prefix to internal/private function names (if they don't have it already)
- Remove `_` prefix from function parameters (if they have it)
- Order function definitions according to the style guide [(1)](https://docs.soliditylang.org/en/v0.8.23/style-guide.html#order-of-functions)

**Comment by guidanoli** [comment]
Let's leave this to last on the release to avoid PR conflicts.

**Comment by ZzzzHui** [comment]
For reference,

- Order of Functions
```
contract A {
    constructor() {
        // ...
    }

    receive() external payable {
        // ...
    }

    fallback() external {
        // ...
    }

    // External functions
    // ...

    // External functions that are view
    // ...

    // External functions that are pure
    // ...

    // Public functions
    // ...

    // Internal functions
    // ...

    // Private functions
    // ...
}
```

- Contract elements should be laid out in the following order
```
Pragma statements
Import statements
Events
Errors
Interfaces
Libraries
Contracts
```
