### ISSUE TITLE
Avoid the use of the word "dApp" in code

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#180]
## 📚 Context

The word "dApp" is short for decentralized application. We often use this word when referring to smart contracts that embody an application in the blockchain. In code, this word often gets capitalized in `PascalCase` as `DApp`. Take the `CartesiDApp` contract as an example. When these names get converted by automatic tools to `snake_case`, for example, the output can be a bit weird, like `cartesi_d_app`.

This problem is relevant because it impacts the legibility of code that is automatically generated from the smart contracts. It does not affect the feature roadmap, nor blocks any other feature. It affects mostly software that uses automatic tools to generate programming language-specific code from our smart contracts.

## ✔️ Solution

We could change how we capitalize the word "dApp", or we could use an easier-to-capitalize word, like "application".
Following this last proposal, contracts like `CartesiDApp` would be renamed as `CartesiApplication`.

**Comment by pedroargento** [comment]
Also remove the word Cartesi to be just `Application` or `IApplication` .

**Comment by guidanoli** [comment]
@pedroargento Yes, this is being tracked by #181.

**Comment by ZzzzHui** [comment]
I suppose we can keep the `dapp` folder name as is. What do you think?

**Comment by guidanoli** [comment]
> I suppose we can keep the `dapp` folder name as is. What do you think?

Yes, let's keep the name of this folder. :-)
