### ISSUE TITLE
Adjust nomenclature used in `IInputBox`

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#203]
## 📚 Context

On #201, we've made some changes to address #2. Most importantly...

- Renamed `input` parameter as `payload`
- Renamed `MAX_INPUT_SIZE` constant as `MAX_INPUT_PAYLOAD_SIZE`
- Added `PayloadTooLarge` custom error

With #84, however, the Server Manager will not write just the payload to the `rx` buffer, but the whole input (payload and metadata) encoded as a Solidity function call.

## ✔️ Solution

We need to make the following adjustments to the `IInputBox` interface...

- Rename `MAX_INPUT_PAYLOAD_SIZE` constant as `MAX_INPUT_SIZE`
- Check if the whole input is smaller than the maximum size, not just the payload
- Rename `PayloadTooLarge` custom error as `InputTooLarge` (and its arguments as well)

**Comment by ZzzzHui** [comment]
Hey Gui. This issue has overlap with the issue https://github.com/cartesi/rollups-contracts/issues/203 and has already been addressed in PR https://github.com/cartesi/rollups-contracts/pull/89, we can either close this issue or link the PR to this too :)

**Comment by guidanoli** [comment]
> This issue has overlap with the issue https://github.com/cartesi/rollups-contracts/issues/203

What do you mean? This is issue #203. :-)

**Comment by guidanoli** [comment]
> we can either close this issue or link the PR to this too :)

Let's link the PR to this issue then.

**Comment by guidanoli** [comment]
> Sorry for the typo. I meant https://github.com/cartesi/rollups-contracts/issues/84 😂

No problem. What is the overlap, though?
