### ISSUE TITLE
Use `abi.encode` for fixed-size values

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#215]
## 📚 Context

There are places in our code base that use `abi.encodePacked` for fixed-size values.
This is not necessary, as `abi.encode` works just like `abi.encodePacked` for those values.
Plus, `abi.encode` is shorter.

## ✔️ Solution

Replace `abi.encodePacked` with `abi.encode` in those cases.

**Comment by ZzzzHui** [comment]
To be exact, by "fixed size" you mean the fixed 32-byte size. Otherwise, for example, `uint64` is fixed size. But `abi.encode` packs it to 32 bytes while `abi.encodePacked` doesn't

**Comment by guidanoli** [comment]
> To be exact, by "fixed size" you mean the fixed 32-byte size. Otherwise, for example, `uint64` is fixed size. But `abi.encode` packs it to 32 bytes while `abi.encodePacked` doesn't

Ouch, you're right!
