### ISSUE TITLE
Remove `ApplicationAddressRelay` contract

### ISSUE THREAD

**Issue by ZzzzHui** [cartesi/rollups-contracts#225]
## 📚 Context

After the issue ["Include the DApp address in the EvmAdvance input"](https://github.com/cartesi/rollups-contracts/issues/144), the contract `ApplicationAddressRelay` would be of no use. So it should be removed. Also need to update documentation and Mermaid graph.

**Comment by guidanoli** [comment]
Why is this tagged as "feature"?

**Comment by ZzzzHui** [comment]
Sorry about that. Now removed.

**Comment by pedroargento** [comment]
This may affect a lot of DApp developers. Maybe we should wait a version before removing it?

**Comment by guidanoli** [comment]
The adaptation should be pretty straightforward, I think.
Any code that expected inputs from the `DAppAddressRelay` would have access to the `sender` metadata field in order to validate the origin of the input. Now, they just need to access the `app` metadata field from any input.

**Comment by guidanoli** [comment]
As for HLF developers, they will have to adapt any input processing logic anyway, because of the Input Simplification. The `app` metadata field will come out from the input blob naturally.
