### ISSUE TITLE
Output Unification

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#42]
## 📚 Context

Currently, the off-chain machine is able to generate two types of outputs: vouchers and notices. On-chain, these outputs can be validated by anyone with the help of validity proofs.

The proof consists on reconstructing the epoch hash and comparing it with the epoch hash that was claimed by the DApp's consensus. If they are equal, then we can be sure the output is valid.

Currently, this epoch hash is composed by the following components.

* The machine Merkle root hash
* The voucher Merkle root hash
* The notice Merkle root hash

As you can see, vouchers and notices each have their own separate Merkle tree. This helps to avoid misinterpreting notices as vouchers and vice versa.

There are, however, two main issues with this design. First, it unnecessarily complicates the on-chain and off-chain code. Second, it hinders the implementation of new output types, since we would have to add a new Merkle tree, which would result in a breaking change in the validation procedure.

## ✔️ Solution

And so, we noticed that things would be much simpler if we had a single tree for all verifiable outputs. To differentiate between output types, we could add a prefix to each output. For example, `0x00` for vouchers and `0x01` for notices. As a result, the epoch hash would only be composed of two components:

* The machine Merkle root hash
* The output Merkle root hash

**Comment by guidanoli** [comment]
Now, from the perspective of the machine, outputs can be thought of as arbitrary blobs. You will be able to tell them apart by the first 4 bytes, which correspond to the function selector of the function call. How this will be reflected on the HTTP API is still under discussion, but some options are:

- The generic approach: outputs are blobs.
  - Pros: Extensible.
  - Cons: User must encode outputs.
- The typed approach: outputs are either notices or outputs or [...]
  - Pros: User-friendly.
  - Cons: Forbids users to emit new types of outputs.
- The mixed approach: outputs are blobs, which can be notices or outputs or [...]
  - Pros: User-friendly and extensible.
  - Cons: User needs to encode outputs not covered by the API.

**Comment by miltonjonat** [comment]
Given that this changes the public API that devs use, maybe it would be nice to consider inputs from the Prototyping and DevAd units. @cf-cartesi @gbarros would you like to comment?

**Comment by guidanoli** [comment]
## Encoding and decoding outputs in Solidity

So, recently I discovered a nice idiomatic, [type-safe](https://docs.soliditylang.org/en/v0.8.22/cheatsheet.html#abi-encoding-and-decoding-functions) way to encode function calls (which we'll be doing a lot). Here's the step-by-step process. I'll link to files from the output unification branch for reference.

1. Define the function in an interface. The nice thing about this approach is that we can use this definition elsewhere, either when encoding or decoding these function calls. You can also easily add documentation in NatSpec format, which can be later used by `solidity-docgen` to generate documentation in Markdown. Furthermore, off-chain code will be able to easily encode/decode data through the contract ABIs and their language bindings. https://github.com/cartesi/rollups-contracts/blob/8c0a23ec835d9b58191a9f60f979526f1410776e/onchain/rollups/contracts/common/Outputs.sol#L9-L20
2. Encode the function call data using `abi.encodeCall`, passing the function pointer as the first argument. After that, the function arguments are passed as a single tuple. And good news: this method is completely type-safe! That means that the compiler will raise an error if you try to encode a function call with the wrong arguments. Language bindings in typed languages will most likely perform these type checks as well. https://github.com/cartesi/rollups-contracts/blob/8c0a23ec835d9b58191a9f60f979526f1410776e/onchain/rollups/test/foundry/dapp/CartesiDApp.t.sol#L728-L732
3. Decode the function call. First, you need to check if the byte array starts with the right selector. For this, I wrote a library called `LibCalldata`, which has a function called `trimSelector`. https://github.com/cartesi/rollups-contracts/blob/8c0a23ec835d9b58191a9f60f979526f1410776e/onchain/rollups/contracts/library/LibCalldata.sol#L14-L24
4. With the selector trimmed, you can decode the function arguments with `abi.decode`. Here, you'll have to specify the argument types, unfortunately.
https://github.com/cartesi/rollups-contracts/blob/8c0a23ec835d9b58191a9f60f979526f1410776e/onchain/rollups/contracts/dapp/CartesiDApp.sol#L140-L143

**Comment by ZzzzHui** [comment]
`abi.encodeCall` was introduced in 0.8.11 and bug fixed in 0.8.13 ([ref](https://soliditylang.org/blog/2022/03/16/encodecall-bug/)), so we probably need `pragma solidity ^0.8.13;`

**Comment by gligneul** [comment]
I created an issue in rollups-node repository to track the changes on our side: https://github.com/cartesi/rollups-node/issues/103

**Comment by mpolitzer** [comment]
The machine-sdk side changes are being tracked here: https://github.com/cartesi/machine-emulator/issues/137

**Comment by guidanoli** [comment]
OpenZeppelin v5 also migrated from `abi.encodeWithSelector` and `abi.encodeWithSignature` to `abi.encodeCall`.
https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4293
