### ISSUE TITLE
Add `Quorum` factory

### ISSUE THREAD

**Issue by pedroargento** [cartesi/rollups-contracts#73]
## 📚 Context

Same context as https://github.com/cartesi/rollups-contracts/issues/25 but for the `Quorum` consensus.

## ✔️ Solution

Create a contract that deploys `Quroum` contracts, ergo an `Quorum` factory.
There would also have to be a script that deploys such factory.

**Comment by guidanoli** [comment]
We should wait until the Quorum contract is consolidated until we take this initiative forward, otherwise there can be a lot of rework.
