### ISSUE TITLE
Blockchain-agnostic Inputs

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#84]
## 📚 Context

Currently, an input is composed of two parts: the input data and the input metadata. The latter includes: the block number and timestamp, the address of whoever sent the input, and the index of the input in the input box.

This, however, exposes to the Cartesi Machine information that is completely EVM-specific, while the Cartesi Machine should be blockchain-agnostic.

## ✔️ Solution

Following the zen of #42, we would like inputs to also be self-contained blobs.

Input payloads are already blobs. So, what we would like to do is ABI-encode the input metadata along with the payload and call it the input blob itself. The hash of this blob will, therefore, constitute as the input hash, which will play a role in arbitration.

Looking far into the future, the Cartesi Machine could be fed with inputs from blockchains other than Ethereum, or we might want to change the blockchain metadata schema. We should, therefore, be able to encode different blockchain metadata and know how to decode it just from a simple inspection of the input blob.

Such type of encoding is possible with the `abi.encodeCall` function, which will also be used to encode outputs. Decoding inputs that are encoded in this way should be straightforward, given that you can identify the input format just by looking at the first four bytes of the blob, which constitutes the function selector, in Solidity terms.

## :memo: Specification

The input metadata is currently composed of the following fields:

- `address sender`: the address of the input sender
- `uint256 blockNumber`: The number of the block in which the input was added
- `uint256 blockTimestamp`: The timestamp of the block in which the input was added (in UNIX epoch format)
- `uint256 index`: The index of the input (in relation to all inputs ever sent to the DApp)

If we are going to use `abi.encodeCall`, we need to decide on the function name that clearly describes the type of input blob. Since this input is coming from an EVM-compatible blockchain, and will trigger an advance request for the off-chain machine, we might call it `EvmAdvance` or `EVMAdvance` (depending on whether you like to keep acronyms capitalized in `PascalCase`). I would generally go for `EVMAdvance`, but I think `EvmAdvance` looks better. The encoding would look something like the following.

```solidity
function EvmAdvance(
    address sender,
    uint256 blockNumber,
    uint256 blockTimestamp,
    uint256 index,
    bytes calldata payload
) external;
```

**Comment by ZzzzHui** [comment]
I don't fully understand this issue probably because I haven't understood the details of how CM synchronizes inputs with inputs on blockchain. My question is, is this `abi.encodeWithSignature` the most straightforward solution, or CM can differentiate inputs from different blockchains based on, for example, rpc links?

**Comment by guidanoli** [comment]
> My question is, is this abi.encodeWithSignature the most straightforward solution, or CM can differentiate inputs from different blockchains based on, for example, rpc links?

I don't know. Are RPC immutable? Can there be multiple RPC links for the same network?

**Comment by mpolitzer** [comment]
Should we have something for `inspect` as well?
There is no "metadata" associated with it.

**Comment by guidanoli** [comment]
Ok, let's rename `EvmInput` to `EvmAdvance`, because it less ambiguous from the point-of-view of the machine.

**Comment by guidanoli** [comment]
Taking into consideration #144 and #145, the new signature should be:

```solidity
function EvmAdvance(
    address sender,
    address dapp,
    uint256 chainId,
    uint256 blockNumber,
    uint256 blockTimestamp,
    uint256 index,
    bytes calldata payload
) external;
```

**Comment by pedroargento** [comment]
`block.prevrandao (uint)` was also discussed. I think its a cool idea so its possible to have some reproducible random number generator available to the DApp.

**Comment by guidanoli** [comment]
> I think its a cool idea so its possible to have some reproducible random number generator available to the DApp.

I think @augustoteixeira could help us assess the quality of this RNG for DApps.

**Comment by pedroargento** [comment]
I think the discussion of the quality of the RNG is super interesting and important, but since it comes from the EVM directly I see no issues in providing it to the DApp and each developer can choose if the randomness is good enough.

Maybe a game that just need some simple randomness without security concerns can use this out of the box.

**Comment by guidanoli** [comment]
> Maybe a game that just need some simple randomness without security concerns can use this out of the box.

My fear is that inattentive DApp developers may use `block.prevrandao` indiscriminately, without considering that users can wait until this value is favourable to add an input.

**Comment by pedroargento** [comment]
I see this problem. But I think a line in the documentation should be enough warning. DApps already depend a lot on developer competency and carefulness and it being a DApp chain it does not affect other DApps.

@felipefg was the one that suggested in Discord, so maybe its a demand from the prototype unit. I want to tag them here but I cant.
