### ISSUE TITLE
Make `CartesiDApp` implement EIP-165

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#87]
## 📚 Context

Currently, the safest way to detect instances of `CartesDApp` is by listening to events emitted by the `CartesiDAppFactory` contract and keeping a set of addresses up-to-date. Some frontends, however, would much benefit from an easier method of detecting `CartesiDApp` contracts.

## ✔️ Solution

One way to do this is by making `CartesiDApp` implement [EIP-165](https://eips.ethereum.org/EIPS/eip-165). This would, of course, have no strong guarantees about the contract creation code, but would give certainty when an address DOES NOT contain `CartesiDApp` code, and could help developers detect bugs, and users detect mistakes.

**Comment by xdaniortega** [comment]
And what about do the implementation of the Graph? We could create a subgraph that queries all events emitted.
I guess this could be a much nicer implementation and would also be more welcomed by the community. 

Usage would be like this:

1. CartesiDapp (or any Cartesi Contract) emit events.
2. Define subgraph and set what events and blockchain to look for.
3. Graph Nodes scan every block looking for this events.
4. dApp can query this data through GraphQL APIs, which get translated by Graph Nodes to fetch indexed data.

**Comment by xdaniortega** [comment]
From a POV of a developer, it is easier to adopt a technology that they already know and that is widely adoptan, rather than implemting yet another EIP.

FYI @cartesi/rollups-unit

**Comment by ZzzzHui** [comment]
> And what about doing the implementation of the Graph? We could create a subgraph that queries all events emitted. I guess this could be a much nicer implementation and would also be more welcomed by the community.
> 
> Usage would be like this:
> 
> 1. CartesiDapp (or any Cartesi Contract) emit events.
> 2. Define subgraph and set what events and blockchain to look for.
> 3. Graph Nodes scan every block looking for this events.
> 4. dApp can query this data through GraphQL APIs, which get translated by Graph Nodes to fetch indexed data.

Hey Daniel. Nice thought but I don't think GraphQL would be applicable here. The current safest way Gui talked about is to listen to one single event (`ApplicationCreated` event). Another way through EIP165, and see what interfaces are implemented.

**Comment by xdaniortega** [comment]
Yeah! In fact the graph offers to query indexed data in the blockchain through APIs. So this issue would be covered by that. We should know what are the requirements of this issue, maybe we are asked to offer a `view` function instead of an API but as first sight, it seems easier to do an API call from UI than to call a `view` function from a contract.

What is it exactly the requirement here? @tuler

**Comment by tuler** [comment]
We already have an indexing project working. Using subsquid, not thegraph.
https://github.com/cartesi/rollups-explorer-api

**Comment by xdaniortega** [comment]
> We already have an indexing project working. Using subsquid, not thegraph.
> https://github.com/cartesi/rollups-explorer-api

So may this solution be used to allow UIs to easily detect instances of `CartesDApp`? 
Were you aware of this solution or is there an specific requirement to implement EIP-165? @guidanoli

**Comment by tuler** [comment]
The indexing solution does not exclude with the EIP-165. They are both useful.

Indexing is centralized. It may not be available.

EIP-165 may not guarantee that a contract is a CartesiDApp, but it certainly help to show that a contract is NOT a CartesiDApp, which is very useful.

So I still think it’s useful.

**Comment by guidanoli** [comment]
> Were you aware of this solution or is there an specific requirement to implement EIP-165? @guidanoli

I was not aware of this solution. The demand comes from @tuler, so we can discuss whether EIP-165 is necessary or not for his use case.

**Comment by guidanoli** [comment]
Just a note here that `CartesiDApp` as of 1.0.0 already implements `supportsInterface` by inheriting `ERC1155Holder` from OpenZeppelin. In 2.0.0, we can make `supportsInterface` return `true` for `type(ICartesiDApp).interfaceId`.
