### ISSUE TITLE
Allow DApps to have ENS names

### ISSUE THREAD

**Issue by guidanoli** [cartesi/rollups-contracts#90]
## 📚 Context

ENS allows users to register human-readable names like `mydapp.eth` for various kinds of data, including Ethereum addresses. This feature might be particularly valuable for users that interact with DApps constantly through UIs that support ENS.

Associating ENS names to Ethereum addresses is pretty straightforward, but the opposite direction requires the owner of the ENS name to call the `setName` function of the ENS reverse registrar. Currently, however, the DApp contract does not have an entry point for this kind of interaction.

## ✔️ Solution

One solution is to add a `setName` function in the DApp contract that can only be called by the DApp owner, and that forwards the call to the ENS reverse registrar. This, however, would incur in a breaking change in the DApp contract, and an increase in the contract bytecode, which is something we should always avoid.

Another solution is to not change the DApp contract at all, but advise the DApp developer to emit a voucher that calls the `setName` function of the ENS reverse registrar with the desired ENS name. This name can be hard-coded in the DApp backend code, or sent through an input from an authorized address. Also, given the network in which the DApp will be deployed, the address of the ENS reverse registrar is easily known.

**Comment by guidanoli** [comment]
@tuler What do you think about the second solution?

**Comment by tuler** [comment]
Not very convenient, but if it works that's ok.

**Comment by guidanoli** [comment]
Yes, it certainly works.
